### ISSUE TITLE
Orientation matching movement direction

### ISSUE THREAD

**Issue by Lyinggod** [strongpauly/swarm#1]
This is a great module. This is a trivial request but orienting each bug so that it is facing the direction it is moving in would be nice. Currently, the orientation of the bug and the direction of movement seem to be completely unrelated.

**Comment by strongpauly** [comment]
Not sure I follow.  Each animation type orients the sprites in the direction of their movement.  The formation animation type orients them in the same direction as the token is facing.

Could you provide an example of what you mean?

**Comment by Lyinggod** [comment]
You are correct. There was some kind of glitch that went away when I refreshed.
