### ISSUE TITLE
[BUG] Massive swarm images after refreshing

### ISSUE THREAD

**Issue by Janner3D** [strongpauly/swarm#2]
**Describe the bug**

**To Reproduce**
1. Place a token on the canvas with a Swarm effect
2. Refresh the page

**Expected behavior**
The images should not be massive after refreshing the page.

**Screenshots**
Before refreshing
![image](https://github.com/user-attachments/assets/78f41434-f869-4ad6-a87d-793a18aa12ad)
After refreshing
![image](https://github.com/user-attachments/assets/f034ebfa-6ad3-407d-a926-25955443c8dc)

**Versions (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Module Version: 12.0.3
 - Foundry Version: 11.315
 - System Version: 3.2.1

**Comment by strongpauly** [comment]
I wasn't able to reproduce this on my Mac with the installed versions (assume you meant dnd5e 3.2.1).  Are there any errors in the console or other steps that you did?

**Comment by strongpauly** [comment]
I've released a new version with some changes to when the swarm sprites scale is calculated.  Could you install this and see if you can reproduce the issue?

**Comment by strongpauly** [comment]
Closing this as no response from OP
